/-
  Thermite/SmtExport.lean — AUTO-GENERATED by `forge/src/lean_smt_export.rs`
  (`.design/stage3-bv-reconstruction.md` REQ-7 / AC-8). DO NOT EDIT BY HAND.

  Each theorem is a per-clause translation-validation obligation `(P_prod) ⟺ (P_ref)`
  emitted by the automated Rust→Lean exporter. QF_LIA uses lean-smt/cvc5. QF_BV is
  rendered directly as `BitVec N` and proved from kernel-checked normalization lemmas.
  The `#print axioms` after each theorem must report a subset of
  {propext, Classical.choice, Quot.sound}.

  The literal QF_BV renderer covers wrapping arithmetic, unsigned comparisons,
  bitwise operations, shifts, unsigned division, and remainder. Regenerate via the
  `golden_file_matches_exporter` test with THERMITE_REGEN_SMT_EXPORT=1.
-/
import Smt

namespace Thermite.SmtExport

theorem thermite_smt_lia_arith_cmp (a b c : Int) :
    ((a - b) ≤ c) ↔ (¬ (c < (a - b))) := by smt
#print axioms thermite_smt_lia_arith_cmp

theorem thermite_smt_bv64_le_not_lt (a b : BitVec 64) :
    (a ≤ b) ↔ (¬ (b < a)) := by
  simp
#print axioms thermite_smt_bv64_le_not_lt

theorem thermite_smt_bv8_add_comm (a b c : BitVec 8) :
    ((a + b) = c) ↔ ((b + a) = c) := by
  simp [BitVec.add_comm]
#print axioms thermite_smt_bv8_add_comm

theorem thermite_smt_bv8_full_terms (a b c : BitVec 8) :
    (((if c = (0#8) then (~~~(0#8)) else ((((((~~~a) &&& b) ||| (a ^^^ b)) <<< c) >>> b) / c)) % b) ≠ ((a * b) + c)) ↔ (¬ (((if c = (0#8) then (~~~(0#8)) else ((((((~~~a) &&& b) ||| (a ^^^ b)) <<< c) >>> b) / c)) % b) = (c + (b * a)))) := by
  simp [BitVec.add_comm, BitVec.mul_comm]
#print axioms thermite_smt_bv8_full_terms

end Thermite.SmtExport
