//! Divergence pin (#130, residual of #127): the SHAPE-keyed byte-view / generated-
//! def shadow (`thermite-lower/src/lower.rs` `user_string_spec_fn_names` +
//! `program_uses_parse`/`program_uses_string_search`/`program_uses_numfmt`) only
//! suppresses the generated def-module emission when the SHADOWED NAME is the *only*
//! trigger. When a program BOTH (a) declares a user `spec fn` whose name collides
//! with a generated byte-view fn (e.g. `spec fn is_digit(s: &String, ..)` /
//! `spec fn count_sep(s: &String, ..)`) AND (b) GENUINELY uses the generated module
//! through a DIFFERENT, non-shadowed trigger (`parse_u64(s)` pulls in the parse
//! module which DEFINES `is_digit(b: u8)`; `s.split(sep)` pulls in the C5 search
//! module which DEFINES `count_sep(s, sep)`), the whole-program `thermite_lower::lower`
//! emits the generated def ALONGSIDE the user def — a DOUBLE DEFINITION (rustc/verus
//! E0428, "the name is defined multiple times"). The lowered Verus source does not
//! compile.
//!
//! AUTHORITY: `.design/basis/07-strings.md` REQ-4 — the byte-view dispatch is
//! SHAPE-derived; a user String-scanning `spec fn` MUST lower + certify L3 and lives
//! in the user namespace, SHADOWING the generated name. A shape-keyed dispatch is
//! collision-free by construction: a generated def whose name a user `spec fn` has
//! claimed must NOT also be materialized. The #127 commit `053190f` states this
//! exact goal in its message ("a user `is_digit` no longer ALSO emits the generated
//! `is_digit` -> E0428 ... so a user-named collision does not emit the generated
//! def"); this test shows that goal is met ONLY when the collided name is the sole
//! trigger, and is VIOLATED when the module is genuinely used via another name.
//! `thermite-design.md` §3 — Thermite lowers to (compilable) Rust/Verus source.
//!
//! R-CHAR-3: the expected value (AT MOST ONE definition per name in the lowered
//! source) is the design property (a closed surface with one definition per name,
//! §4.4 / REQ-4's namespace claim), NOT copied from the toolchain's own output. The
//! control case (a NON-colliding user name `scan`/`piece` + the same generated use)
//! lowers with exactly one generated def — pinning that the divergence is the NAME
//! COLLISION, not the generated emission itself.

fn lower_ok(prog: &str) -> String {
    let parsed = thermite_syntax::parse(prog);
    assert!(
        parsed.errors.is_empty(),
        "parse errors: {:?}",
        parsed.errors
    );
    thermite_lower::lower(&parsed.program).expect("lower must not hard-error")
}

fn def_count(src: &str, name_decl: &str) -> usize {
    // count source lines that DECLARE a fn `name` (a `fn <name>(` / `spec fn <name>(`
    // signature line) — a definition site, not a call.
    src.lines()
        .filter(|l| {
            let t = l.trim_start();
            (t.contains(&format!("fn {name_decl}(")) || t.contains(&format!("fn {name_decl} ")))
                && (t.starts_with("fn ")
                    || t.starts_with("pub fn ")
                    || t.starts_with("spec fn ")
                    || t.starts_with("pub spec fn ")
                    || t.starts_with("pub open spec fn ")
                    || t.starts_with("open spec fn "))
        })
        .count()
}

// (#130) A user `spec fn is_digit(s: &String, ..)` collides with the GENERATED
// `is_digit(b: u8)` that `parse_u64(s)` (a non-shadowed trigger) materializes. The
// whole-program lowering emits BOTH -> E0428. A correct shape-keyed dispatch yields
// at most one `is_digit` definition.
#[test]
#[ignore = "blocker #130 — un-ignore when fixed"]
fn user_isdigit_plus_genuine_parse_use_no_double_def() {
    // CONTROL: a NON-colliding user name (`scan`) + the same `parse_u64(s)` use ->
    // exactly one generated `is_digit` def (the divergence is the collision, not the
    // generated emission).
    let control = r#"
spec fn scan(s: &String, i: u64) -> bool
  dec i
{ if i == 0 { true } else { scan(s, i - 1) } }

fn p(s: &String) -> Option<u64>
  req true
  ens true
  fx  pure
{ parse_u64(s) }
"#;
    assert_eq!(
        def_count(&lower_ok(control), "is_digit"),
        1,
        "CONTROL: a non-colliding program must emit exactly one generated `is_digit`; \
         if this fails the fixture is wrong, not the toolchain"
    );

    // DIVERGENCE: rename the user spec fn to `is_digit` (a GENERATED_PARSE_FNS name).
    // The byte-view shadow excludes it from the emission GATE, but `parse_u64(s)` is
    // an independent, non-shadowed trigger that materializes the parse module —
    // including its own `is_digit(b: u8)` — alongside the user `is_digit(&String,..)`.
    let collide = control.replace("scan", "is_digit");
    let n = def_count(&lower_ok(&collide), "is_digit");
    assert!(
        n <= 1,
        "DIVERGENCE (#130): a user `spec fn is_digit(&String,..)` that coexists with a \
         genuine `parse_u64(s)` use must NOT double-define `is_digit` — the SHAPE-keyed \
         dispatch (07-strings.md REQ-4) must be collision-free, but the lowering emitted \
         {n} definitions of `is_digit` (E0428)"
    );
}

// (#130) The C5 search analogue: a user `spec fn count_sep(s: &String, ..)` collides
// with the GENERATED `count_sep` that `s.split(sep)` materializes -> E0428.
#[test]
#[ignore = "blocker #130 — un-ignore when fixed"]
fn user_countsep_plus_genuine_split_use_no_double_def() {
    let control = r#"
spec fn piece(s: &String, i: u64) -> u64
  dec i
{ if i == 0 { 0 } else { piece(s, i - 1) } }

fn p(s: &String) -> Vec<String>
  req true
  ens true
  fx  alloc
{ s.split(44) }
"#;
    assert_eq!(
        def_count(&lower_ok(control), "count_sep"),
        1,
        "CONTROL: a non-colliding program must emit exactly one generated `count_sep`"
    );

    let collide = control.replace("piece", "count_sep");
    let n = def_count(&lower_ok(&collide), "count_sep");
    assert!(
        n <= 1,
        "DIVERGENCE (#130): a user `spec fn count_sep(&String,..)` that coexists with a \
         genuine `s.split(sep)` use must NOT double-define `count_sep` (07-strings.md \
         REQ-4, collision-free) — the lowering emitted {n} definitions (E0428)"
    );
}
